### ISSUE TITLE
Can Nimbus Roman No9 L replaced by TeX Gyre Termes?

### ISSUE THREAD

**Issue by koppor** [sieversMartin/CID#2]
I am trying to fix

    luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: File not found: "NimbusRomNo9L-Reg.otf".

at https://github.com/koppor/CID/pull/1

Thereby, I found https://ask.libreoffice.org/t/nimbus-roman-no9-l-font-missing-in-writer/27803/4.

Would usage of TeX Gyre Termes a solution here, too?

**Comment by koppor** [comment]
No. See https://github.com/sieversMartin/CID/issues/1#issuecomment-1885222643.

**Comment by sieversMartin** [comment]
Well, I wouldn't strictly say "No". It could be an option. 
Regarding your original problem: The files you need were sent to me by the publisher, but I guess, that are not part of TeX Live and not open.

**Comment by sieversMartin** [comment]
We should maybe add a comment in the documentation about the availability of the OpenType font.

The situation is somewhat strange as there are commercial offers (see https://www.linotype.com/de/2996337/nimbus-roman-no-9-schriftfamilie.html or https://www.myfonts.com/de/collections/nimbus-roman-no-9-font-urw?queryId=&eventName=Product%20Clicked&index=universal_search_data&objectIDs=5423416002&positions=1) as well as free variants: https://www.fontsquirrel.com/fonts/nimbus-roman-no9-l which refers to Ghostscript's repo at https://git.ghostscript.com/?p=user/tor/urw-base-12.git)

**Comment by koppor** [comment]
I managed to generate the files on Linux. On Windows, I just googled and took the first google hit ^^.

They should be distributable as free software - [according to WikiPedia](https://en.wikipedia.org/wiki/Nimbus_Roman_No._9_L).

Maybe, we convince the publisher to use the really free font Tex Gyre, because it is (somehow) also my money given to the development of the project...
